# Generated by Django 4.0 on 2021-12-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product_storage',
            table='products_storages',
        ),
    ]
