# Generated by Django 4.0 on 2021-12-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_storage_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Storage',
            new_name='ProductStorage',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='detail_image',
            new_name='detail_url',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='main_image',
            new_name='main_url',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
